# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: main
  schedule:
    - cron: '0 1 * * *'


name: render website

jobs:
  render:
    name: Rebuild Website
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v1
      
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Install distill
        run: Rscript -e 'install.packages("tidyverse")'
      - name: Install httr
        run: Rscript -e 'install.packages("httr")'
      - name: Install jsonlite
        run: Rscript -e 'install.packages("jsonlite")'
      - name: Install here
        run: Rscript -e 'install.packages("rtide")'
      - name: Install tidyverse
        run: Rscript -e 'install.packages("glue")'
      - name: Install emojifont
        run: Rscript -e 'install.packages("lubridate")'
      - name: Install DT
        run: Rscript -e 'install.packages("ggpmisc")'
      - name: Install janitor
        run: Rscript -e 'install.packages("htmltools")'
        
      - name: Get data from clinicaltrials.gov and rebuild site
        env: 
          MAPBOX: ${{ secrets.WEATHER }}

      - name: Render Rmarkdown files and Commit Results
        run: |
          echo "Rendering the page..."
          Rscript -e 'rmarkdown::render(input = "index.Rmd")'
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add *
            git commit -m "Auto update Report"
            git push origin
          fi